//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.6.81.0 です。
// 

// 質問詳細
namespace chieviewer.Api.detailSearchResponse
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:yahoo:jp:chiebukuro", IsNullable = false)]
    public partial class ResultSet
    {

        private ResultSetStatus statusField;

        private ResultSetResult resultField;

        private string totalResultsAvailableField;

        private string totalResultsReturnedField;

        private string firstResultPositionField;

        private string maxPositionField;

        private string nextFirstPositionField;

        private string prevFirstPositionField;

        private string nextPageField;

        private string prevPageField;

        private string maxPageField;

        private string maxItemsField;

        /// <remarks/>
        public ResultSetStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public ResultSetResult Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string totalResultsAvailable
        {
            get
            {
                return this.totalResultsAvailableField;
            }
            set
            {
                this.totalResultsAvailableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string totalResultsReturned
        {
            get
            {
                return this.totalResultsReturnedField;
            }
            set
            {
                this.totalResultsReturnedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string firstResultPosition
        {
            get
            {
                return this.firstResultPositionField;
            }
            set
            {
                this.firstResultPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string maxPosition
        {
            get
            {
                return this.maxPositionField;
            }
            set
            {
                this.maxPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string nextFirstPosition
        {
            get
            {
                return this.nextFirstPositionField;
            }
            set
            {
                this.nextFirstPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string prevFirstPosition
        {
            get
            {
                return this.prevFirstPositionField;
            }
            set
            {
                this.prevFirstPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string nextPage
        {
            get
            {
                return this.nextPageField;
            }
            set
            {
                this.nextPageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string prevPage
        {
            get
            {
                return this.prevPageField;
            }
            set
            {
                this.prevPageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string maxPage
        {
            get
            {
                return this.maxPageField;
            }
            set
            {
                this.maxPageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string maxItems
        {
            get
            {
                return this.maxItemsField;
            }
            set
            {
                this.maxItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetStatus
    {

        private ResultSetStatusArgs argsField;

        /// <remarks/>
        public ResultSetStatusArgs Args
        {
            get
            {
                return this.argsField;
            }
            set
            {
                this.argsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetStatusArgs
    {

        private string appidField;

        private string _srcField;

        private string question_idField;

        private string sortField;

        private string answer_idField;

        private string master_flagField;

        private string startField;

        private string pageField;

        private string resultsField;

        private string debugField;

        private string res_typeField;

        private string view_increment_flagField;

        private string yidField;

        private string use_titleField;

        private string outputField;

        private string extendField;

        private string delete_flagField;

        private string delete_reason_flagField;

        private string image_typeField;

        private string no_error_flagField;

        private string user_info_flagField;

        private string refreshField;

        /// <remarks/>
        public string appid
        {
            get
            {
                return this.appidField;
            }
            set
            {
                this.appidField = value;
            }
        }

        /// <remarks/>
        public string _src
        {
            get
            {
                return this._srcField;
            }
            set
            {
                this._srcField = value;
            }
        }

        /// <remarks/>
        public string question_id
        {
            get
            {
                return this.question_idField;
            }
            set
            {
                this.question_idField = value;
            }
        }

        /// <remarks/>
        public string sort
        {
            get
            {
                return this.sortField;
            }
            set
            {
                this.sortField = value;
            }
        }

        /// <remarks/>
        public string answer_id
        {
            get
            {
                return this.answer_idField;
            }
            set
            {
                this.answer_idField = value;
            }
        }

        /// <remarks/>
        public string master_flag
        {
            get
            {
                return this.master_flagField;
            }
            set
            {
                this.master_flagField = value;
            }
        }

        /// <remarks/>
        public string start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }

        /// <remarks/>
        public string page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        /// <remarks/>
        public string results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }

        /// <remarks/>
        public string debug
        {
            get
            {
                return this.debugField;
            }
            set
            {
                this.debugField = value;
            }
        }

        /// <remarks/>
        public string res_type
        {
            get
            {
                return this.res_typeField;
            }
            set
            {
                this.res_typeField = value;
            }
        }

        /// <remarks/>
        public string view_increment_flag
        {
            get
            {
                return this.view_increment_flagField;
            }
            set
            {
                this.view_increment_flagField = value;
            }
        }

        /// <remarks/>
        public string yid
        {
            get
            {
                return this.yidField;
            }
            set
            {
                this.yidField = value;
            }
        }

        /// <remarks/>
        public string use_title
        {
            get
            {
                return this.use_titleField;
            }
            set
            {
                this.use_titleField = value;
            }
        }

        /// <remarks/>
        public string output
        {
            get
            {
                return this.outputField;
            }
            set
            {
                this.outputField = value;
            }
        }

        /// <remarks/>
        public string extend
        {
            get
            {
                return this.extendField;
            }
            set
            {
                this.extendField = value;
            }
        }

        /// <remarks/>
        public string delete_flag
        {
            get
            {
                return this.delete_flagField;
            }
            set
            {
                this.delete_flagField = value;
            }
        }

        /// <remarks/>
        public string delete_reason_flag
        {
            get
            {
                return this.delete_reason_flagField;
            }
            set
            {
                this.delete_reason_flagField = value;
            }
        }

        /// <remarks/>
        public string image_type
        {
            get
            {
                return this.image_typeField;
            }
            set
            {
                this.image_typeField = value;
            }
        }

        /// <remarks/>
        public string no_error_flag
        {
            get
            {
                return this.no_error_flagField;
            }
            set
            {
                this.no_error_flagField = value;
            }
        }

        /// <remarks/>
        public string user_info_flag
        {
            get
            {
                return this.user_info_flagField;
            }
            set
            {
                this.user_info_flagField = value;
            }
        }

        /// <remarks/>
        public string refresh
        {
            get
            {
                return this.refreshField;
            }
            set
            {
                this.refreshField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class answerSet
    {

        private string answerIdField;

        private string answerStatusField;

        private string contentField;

        private string answerPostDateField;

        private string answerEditDateField;

        private string nickNameField;

        private string isMobileField;

        private string attributeCodeField;

        private string gradeField;

        private string agreeField;

        private string myPageUrlField;

        private answerSetImage imageField;

        private string deleteReasonCodeField;

        private string companyFlagField;

        private string userIdField;

        private string isPublicField;

        private string answerStatusNumField;

        private string lifeField;

        private string totalPointField;

        private string profileImageFlagField;

        private string knowledgeQuestionCountField;

        private string questionDeleteCountField;

        private string normalAnswerCountField;

        private string answerDeleteCountField;

        private string bestAnswerCountField;

        private ResultSetResultSpecialUser specialUserField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string AnswerId
        {
            get
            {
                return this.answerIdField;
            }
            set
            {
                this.answerIdField = value;
            }
        }

        /// <remarks/>
        public string AnswerStatus
        {
            get
            {
                return this.answerStatusField;
            }
            set
            {
                this.answerStatusField = value;
            }
        }

        /// <remarks/>
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        public string AnswerPostDate
        {
            get
            {
                return this.answerPostDateField;
            }
            set
            {
                this.answerPostDateField = value;
            }
        }

        /// <remarks/>
        public string AnswerEditDate
        {
            get
            {
                return this.answerEditDateField;
            }
            set
            {
                this.answerEditDateField = value;
            }
        }

        /// <remarks/>
        public string NickName
        {
            get
            {
                return this.nickNameField;
            }
            set
            {
                this.nickNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string IsMobile
        {
            get
            {
                return this.isMobileField;
            }
            set
            {
                this.isMobileField = value;
            }
        }

        /// <remarks/>
        public string AttributeCode
        {
            get
            {
                return this.attributeCodeField;
            }
            set
            {
                this.attributeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Agree
        {
            get
            {
                return this.agreeField;
            }
            set
            {
                this.agreeField = value;
            }
        }

        /// <remarks/>
        public string MyPageUrl
        {
            get
            {
                return this.myPageUrlField;
            }
            set
            {
                this.myPageUrlField = value;
            }
        }

        /// <remarks/>
        public answerSetImage Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string DeleteReasonCode
        {
            get
            {
                return this.deleteReasonCodeField;
            }
            set
            {
                this.deleteReasonCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string CompanyFlag
        {
            get
            {
                return this.companyFlagField;
            }
            set
            {
                this.companyFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string IsPublic
        {
            get
            {
                return this.isPublicField;
            }
            set
            {
                this.isPublicField = value;
            }
        }

        /// <remarks/>
        public string AnswerStatusNum
        {
            get
            {
                return this.answerStatusNumField;
            }
            set
            {
                this.answerStatusNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Life
        {
            get
            {
                return this.lifeField;
            }
            set
            {
                this.lifeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string TotalPoint
        {
            get
            {
                return this.totalPointField;
            }
            set
            {
                this.totalPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string ProfileImageFlag
        {
            get
            {
                return this.profileImageFlagField;
            }
            set
            {
                this.profileImageFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string KnowledgeQuestionCount
        {
            get
            {
                return this.knowledgeQuestionCountField;
            }
            set
            {
                this.knowledgeQuestionCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string QuestionDeleteCount
        {
            get
            {
                return this.questionDeleteCountField;
            }
            set
            {
                this.questionDeleteCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string NormalAnswerCount
        {
            get
            {
                return this.normalAnswerCountField;
            }
            set
            {
                this.normalAnswerCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string AnswerDeleteCount
        {
            get
            {
                return this.answerDeleteCountField;
            }
            set
            {
                this.answerDeleteCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string BestAnswerCount
        {
            get
            {
                return this.bestAnswerCountField;
            }
            set
            {
                this.bestAnswerCountField = value;
            }
        }

        /// <remarks/>
        public ResultSetResultSpecialUser SpecialUser
        {
            get
            {
                return this.specialUserField;
            }
            set
            {
                this.specialUserField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class answerSetImage
    {

        private string widthField;

        private string heightField;

        private string urlField;

        public answerSetImage()
        {
            this.widthField = "0";
            this.heightField = "0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultSpecialUser
    {

        private string iconTypeField;

        private string urlField;

        private ResultSetResultSpecialUserImageSmall imageSmallField;

        private ResultSetResultSpecialUserImageBig imageBigField;

        private string titleField;

        private string statusField;

        private string subStatusField;

        private ResultSetResultSpecialUserBanner bannerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string IconType
        {
            get
            {
                return this.iconTypeField;
            }
            set
            {
                this.iconTypeField = value;
            }
        }

        /// <remarks/>
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public ResultSetResultSpecialUserImageSmall ImageSmall
        {
            get
            {
                return this.imageSmallField;
            }
            set
            {
                this.imageSmallField = value;
            }
        }

        /// <remarks/>
        public ResultSetResultSpecialUserImageBig ImageBig
        {
            get
            {
                return this.imageBigField;
            }
            set
            {
                this.imageBigField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string SubStatus
        {
            get
            {
                return this.subStatusField;
            }
            set
            {
                this.subStatusField = value;
            }
        }

        /// <remarks/>
        public ResultSetResultSpecialUserBanner Banner
        {
            get
            {
                return this.bannerField;
            }
            set
            {
                this.bannerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultSpecialUserImageSmall
    {

        private ResultSetResultSpecialUserImageSmallImage imageField;

        /// <remarks/>
        public ResultSetResultSpecialUserImageSmallImage Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultSpecialUserImageSmallImage
    {

        private string widthField;

        private string heightField;

        private string urlField;

        private string altField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string Alt
        {
            get
            {
                return this.altField;
            }
            set
            {
                this.altField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultSpecialUserImageBig
    {

        private ResultSetResultSpecialUserImageBigImage imageField;

        /// <remarks/>
        public ResultSetResultSpecialUserImageBigImage Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultSpecialUserImageBigImage
    {

        private string widthField;

        private string heightField;

        private string urlField;

        private string altField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string Alt
        {
            get
            {
                return this.altField;
            }
            set
            {
                this.altField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultSpecialUserBanner
    {

        private ResultSetResultSpecialUserBannerImage imageField;

        /// <remarks/>
        public ResultSetResultSpecialUserBannerImage Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultSpecialUserBannerImage
    {

        private string widthField;

        private string heightField;

        private string urlField;

        private string altField;

        private string textField;

        private string noField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string Alt
        {
            get
            {
                return this.altField;
            }
            set
            {
                this.altField = value;
            }
        }

        /// <remarks/>
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResult
    {

        private string questionIdField;

        private string categoryIdField;

        private string spaceIdDetailField;

        private string questionNumField;

        private string titleField;

        private string contentField;

        private string supplementContentField;

        private string bestAnswerContentField;

        private string viewCountField;

        private string voteCountField;

        private string reviewCountField;

        private string questionPostDateField;

        private string questionEditDateField;

        private string questionVoteDateField;

        private string questionEndDateField;

        private string questionFinishDateField;

        private string rewardDateField;

        private string rewardField;

        private string rewardIconField;

        private string yidField;

        private string nickNameField;

        private string pcQuestionUrlField;

        private string mobileQuestionUrlField;

        private string myPageUrlField;

        private string isMobileField;

        private ResultSetResultImage imageField;

        private string attributeCodeField;

        private string categoryIdPathField;

        private string categoryField;

        private string categoryPathField;

        private string questionStatusField;

        private string answerCountField;

        private string coinField;

        private string helpCountField;

        private string newListDisplayFlagField;

        private string makeTitleFlagField;

        private string companyFlagField;

        private string goodRateCountField;

        private string badRateCountField;

        private string gradeField;

        private string agreeField;

        private string userQuestionStatusField;

        private string userAnswerStatusField;

        private string userAnswerIdField;

        private string deleteReasonCodeField;

        private string userIdField;

        private string questionStatusNumField;

        private string isPublicField;

        private string isVotedField;

        private string isRatedField;

        private string questionTypeField;

        private string voteAnswerIdField;

        private string lifeField;

        private string totalPointField;

        private string profileImageFlagField;

        private string knowledgeQuestionCountField;

        private string questionDeleteCountField;

        private string normalAnswerCountField;

        private string answerDeleteCountField;

        private string bestAnswerCountField;

        private ResultSetResultSpecialUser specialUserField;

        private ResultSetResultAnswerList answerListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string QuestionId
        {
            get
            {
                return this.questionIdField;
            }
            set
            {
                this.questionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string SpaceIdDetail
        {
            get
            {
                return this.spaceIdDetailField;
            }
            set
            {
                this.spaceIdDetailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string QuestionNum
        {
            get
            {
                return this.questionNumField;
            }
            set
            {
                this.questionNumField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        public string SupplementContent
        {
            get
            {
                return this.supplementContentField;
            }
            set
            {
                this.supplementContentField = value;
            }
        }

        /// <remarks/>
        public string BestAnswerContent
        {
            get
            {
                return this.bestAnswerContentField;
            }
            set
            {
                this.bestAnswerContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string ViewCount
        {
            get
            {
                return this.viewCountField;
            }
            set
            {
                this.viewCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string VoteCount
        {
            get
            {
                return this.voteCountField;
            }
            set
            {
                this.voteCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string ReviewCount
        {
            get
            {
                return this.reviewCountField;
            }
            set
            {
                this.reviewCountField = value;
            }
        }

        /// <remarks/>
        public string QuestionPostDate
        {
            get
            {
                return this.questionPostDateField;
            }
            set
            {
                this.questionPostDateField = value;
            }
        }

        /// <remarks/>
        public string QuestionEditDate
        {
            get
            {
                return this.questionEditDateField;
            }
            set
            {
                this.questionEditDateField = value;
            }
        }

        /// <remarks/>
        public string QuestionVoteDate
        {
            get
            {
                return this.questionVoteDateField;
            }
            set
            {
                this.questionVoteDateField = value;
            }
        }

        /// <remarks/>
        public string QuestionEndDate
        {
            get
            {
                return this.questionEndDateField;
            }
            set
            {
                this.questionEndDateField = value;
            }
        }

        /// <remarks/>
        public string QuestionFinishDate
        {
            get
            {
                return this.questionFinishDateField;
            }
            set
            {
                this.questionFinishDateField = value;
            }
        }

        /// <remarks/>
        public string RewardDate
        {
            get
            {
                return this.rewardDateField;
            }
            set
            {
                this.rewardDateField = value;
            }
        }

        /// <remarks/>
        public string Reward
        {
            get
            {
                return this.rewardField;
            }
            set
            {
                this.rewardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string RewardIcon
        {
            get
            {
                return this.rewardIconField;
            }
            set
            {
                this.rewardIconField = value;
            }
        }

        /// <remarks/>
        public string Yid
        {
            get
            {
                return this.yidField;
            }
            set
            {
                this.yidField = value;
            }
        }

        /// <remarks/>
        public string NickName
        {
            get
            {
                return this.nickNameField;
            }
            set
            {
                this.nickNameField = value;
            }
        }

        /// <remarks/>
        public string PcQuestionUrl
        {
            get
            {
                return this.pcQuestionUrlField;
            }
            set
            {
                this.pcQuestionUrlField = value;
            }
        }

        /// <remarks/>
        public string MobileQuestionUrl
        {
            get
            {
                return this.mobileQuestionUrlField;
            }
            set
            {
                this.mobileQuestionUrlField = value;
            }
        }

        /// <remarks/>
        public string MyPageUrl
        {
            get
            {
                return this.myPageUrlField;
            }
            set
            {
                this.myPageUrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string IsMobile
        {
            get
            {
                return this.isMobileField;
            }
            set
            {
                this.isMobileField = value;
            }
        }

        /// <remarks/>
        public ResultSetResultImage Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        public string AttributeCode
        {
            get
            {
                return this.attributeCodeField;
            }
            set
            {
                this.attributeCodeField = value;
            }
        }

        /// <remarks/>
        public string CategoryIdPath
        {
            get
            {
                return this.categoryIdPathField;
            }
            set
            {
                this.categoryIdPathField = value;
            }
        }

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public string CategoryPath
        {
            get
            {
                return this.categoryPathField;
            }
            set
            {
                this.categoryPathField = value;
            }
        }

        /// <remarks/>
        public string QuestionStatus
        {
            get
            {
                return this.questionStatusField;
            }
            set
            {
                this.questionStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string AnswerCount
        {
            get
            {
                return this.answerCountField;
            }
            set
            {
                this.answerCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Coin
        {
            get
            {
                return this.coinField;
            }
            set
            {
                this.coinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string HelpCount
        {
            get
            {
                return this.helpCountField;
            }
            set
            {
                this.helpCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string NewListDisplayFlag
        {
            get
            {
                return this.newListDisplayFlagField;
            }
            set
            {
                this.newListDisplayFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string MakeTitleFlag
        {
            get
            {
                return this.makeTitleFlagField;
            }
            set
            {
                this.makeTitleFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string CompanyFlag
        {
            get
            {
                return this.companyFlagField;
            }
            set
            {
                this.companyFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string GoodRateCount
        {
            get
            {
                return this.goodRateCountField;
            }
            set
            {
                this.goodRateCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string BadRateCount
        {
            get
            {
                return this.badRateCountField;
            }
            set
            {
                this.badRateCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Agree
        {
            get
            {
                return this.agreeField;
            }
            set
            {
                this.agreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string UserQuestionStatus
        {
            get
            {
                return this.userQuestionStatusField;
            }
            set
            {
                this.userQuestionStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string UserAnswerStatus
        {
            get
            {
                return this.userAnswerStatusField;
            }
            set
            {
                this.userAnswerStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string UserAnswerId
        {
            get
            {
                return this.userAnswerIdField;
            }
            set
            {
                this.userAnswerIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string DeleteReasonCode
        {
            get
            {
                return this.deleteReasonCodeField;
            }
            set
            {
                this.deleteReasonCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string QuestionStatusNum
        {
            get
            {
                return this.questionStatusNumField;
            }
            set
            {
                this.questionStatusNumField = value;
            }
        }

        /// <remarks/>
        public string IsPublic
        {
            get
            {
                return this.isPublicField;
            }
            set
            {
                this.isPublicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string IsVoted
        {
            get
            {
                return this.isVotedField;
            }
            set
            {
                this.isVotedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string IsRated
        {
            get
            {
                return this.isRatedField;
            }
            set
            {
                this.isRatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string QuestionType
        {
            get
            {
                return this.questionTypeField;
            }
            set
            {
                this.questionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string VoteAnswerId
        {
            get
            {
                return this.voteAnswerIdField;
            }
            set
            {
                this.voteAnswerIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Life
        {
            get
            {
                return this.lifeField;
            }
            set
            {
                this.lifeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string TotalPoint
        {
            get
            {
                return this.totalPointField;
            }
            set
            {
                this.totalPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string ProfileImageFlag
        {
            get
            {
                return this.profileImageFlagField;
            }
            set
            {
                this.profileImageFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string KnowledgeQuestionCount
        {
            get
            {
                return this.knowledgeQuestionCountField;
            }
            set
            {
                this.knowledgeQuestionCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string QuestionDeleteCount
        {
            get
            {
                return this.questionDeleteCountField;
            }
            set
            {
                this.questionDeleteCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string NormalAnswerCount
        {
            get
            {
                return this.normalAnswerCountField;
            }
            set
            {
                this.normalAnswerCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string AnswerDeleteCount
        {
            get
            {
                return this.answerDeleteCountField;
            }
            set
            {
                this.answerDeleteCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string BestAnswerCount
        {
            get
            {
                return this.bestAnswerCountField;
            }
            set
            {
                this.bestAnswerCountField = value;
            }
        }

        /// <remarks/>
        public ResultSetResultSpecialUser SpecialUser
        {
            get
            {
                return this.specialUserField;
            }
            set
            {
                this.specialUserField = value;
            }
        }

        /// <remarks/>
        public ResultSetResultAnswerList AnswerList
        {
            get
            {
                return this.answerListField;
            }
            set
            {
                this.answerListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultImage
    {

        private string widthField;

        private string heightField;

        private string urlField;

        public ResultSetResultImage()
        {
            this.widthField = "0";
            this.heightField = "0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResultAnswerList
    {

        private answerSet bestAnswerField;

        private answerSet[] answerField;

        /// <remarks/>
        public answerSet BestAnswer
        {
            get
            {
                return this.bestAnswerField;
            }
            set
            {
                this.bestAnswerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Answer")]
        public answerSet[] Answer
        {
            get
            {
                return this.answerField;
            }
            set
            {
                this.answerField = value;
            }
        }
    }
}