//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.6.81.0 です。
// 

// 新着質問リスト取得
namespace chieviewer.Api.getNewQuestionList
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:yahoo:jp:chiebukuro", IsNullable = false)]
    public partial class ResultSet
    {

        private ResultSetResult[] resultField;

        private string totalResultsAvailableField;

        private string totalResultsReturnedField;

        private string firstResultPositionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Result")]
        public ResultSetResult[] Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string totalResultsAvailable
        {
            get
            {
                return this.totalResultsAvailableField;
            }
            set
            {
                this.totalResultsAvailableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string totalResultsReturned
        {
            get
            {
                return this.totalResultsReturnedField;
            }
            set
            {
                this.totalResultsReturnedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string firstResultPosition
        {
            get
            {
                return this.firstResultPositionField;
            }
            set
            {
                this.firstResultPositionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetResult
    {

        private string questionIdField;

        private string questionUrlField;

        private string contentField;

        private string categoryIdField;

        private string categoryField;

        private string categoryPathField;

        private bool isMobileField;

        private bool hasImageField;

        private string ansCountField;

        private string coinField;

        private string bestAnswerField;

        private string updatedDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string QuestionId
        {
            get
            {
                return this.questionIdField;
            }
            set
            {
                this.questionIdField = value;
            }
        }

        /// <remarks/>
        public string QuestionUrl
        {
            get
            {
                return this.questionUrlField;
            }
            set
            {
                this.questionUrlField = value;
            }
        }

        /// <remarks/>
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public string CategoryPath
        {
            get
            {
                return this.categoryPathField;
            }
            set
            {
                this.categoryPathField = value;
            }
        }

        /// <remarks/>
        public bool IsMobile
        {
            get
            {
                return this.isMobileField;
            }
            set
            {
                this.isMobileField = value;
            }
        }

        /// <remarks/>
        public bool HasImage
        {
            get
            {
                return this.hasImageField;
            }
            set
            {
                this.hasImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string AnsCount
        {
            get
            {
                return this.ansCountField;
            }
            set
            {
                this.ansCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Coin
        {
            get
            {
                return this.coinField;
            }
            set
            {
                this.coinField = value;
            }
        }

        /// <remarks/>
        public string BestAnswer
        {
            get
            {
                return this.bestAnswerField;
            }
            set
            {
                this.bestAnswerField = value;
            }
        }

        /// <remarks/>
        public string UpdatedDate
        {
            get
            {
                return this.updatedDateField;
            }
            set
            {
                this.updatedDateField = value;
            }
        }
    }
}