//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 

namespace chieviewer.Api.questionSearchResponse
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:yahoo:jp:chiebukuro", IsNullable = false)]
    public partial class ResultSet
    {

        private ResultSetStatus statusField;

        private ResultSetQuestion[] resultField;

        private string totalResultsReturnedField;

        private string totalResultsAvailableField;

        private string firstResultPositionField;

        /// <remarks/>
        public ResultSetStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Question", IsNullable = false)]
        public ResultSetQuestion[] Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string totalResultsReturned
        {
            get
            {
                return this.totalResultsReturnedField;
            }
            set
            {
                this.totalResultsReturnedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string totalResultsAvailable
        {
            get
            {
                return this.totalResultsAvailableField;
            }
            set
            {
                this.totalResultsAvailableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string firstResultPosition
        {
            get
            {
                return this.firstResultPositionField;
            }
            set
            {
                this.firstResultPositionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetStatus
    {

        private ResultSetStatusError errorField;

        /// <remarks/>
        public ResultSetStatusError Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetStatusError
    {

        private string messageField;

        private string codeField;

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:yahoo:jp:chiebukuro")]
    public partial class ResultSetQuestion
    {

        private string idField;

        private string contentField;

        private string bestAnswerField;

        private string urlField;

        private string conditionField;

        private string categoryPathField;

        private string categoryIdPathField;

        private string ansCountField;

        private string postedDateField;

        private string solvedDateField;

        private string postedDeviceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        public string BestAnswer
        {
            get
            {
                return this.bestAnswerField;
            }
            set
            {
                this.bestAnswerField = value;
            }
        }

        /// <remarks/>
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        public string CategoryPath
        {
            get
            {
                return this.categoryPathField;
            }
            set
            {
                this.categoryPathField = value;
            }
        }

        /// <remarks/>
        public string CategoryIdPath
        {
            get
            {
                return this.categoryIdPathField;
            }
            set
            {
                this.categoryIdPathField = value;
            }
        }

        /// <remarks/>
        public string AnsCount
        {
            get
            {
                return this.ansCountField;
            }
            set
            {
                this.ansCountField = value;
            }
        }

        /// <remarks/>
        public string PostedDate
        {
            get
            {
                return this.postedDateField;
            }
            set
            {
                this.postedDateField = value;
            }
        }

        /// <remarks/>
        public string SolvedDate
        {
            get
            {
                return this.solvedDateField;
            }
            set
            {
                this.solvedDateField = value;
            }
        }

        /// <remarks/>
        public string PostedDevice
        {
            get
            {
                return this.postedDeviceField;
            }
            set
            {
                this.postedDeviceField = value;
            }
        }
    }
}